version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis
  app:
    build: .
    volumes:
      - bundle:/bundle
  web:
    extends:
      service: app
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
      - redis
  worker:
    extends:
      service: app
    command: bundle exec sidekiq
    volumes:
      - .:/app
    links:
      - db
      - redis
volumes:
  db-data:
    driver: local
  bundle:
    driver: local
